//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saeed.Utilities.LocalizedResource.ErrorMessages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Saeed.Utilities.LocalizedResource.ErrorMessages.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied !.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Recover account at this time..
        /// </summary>
        public static string AccountRecoveryNotAvailable {
            get {
                return ResourceManager.GetString("AccountRecoveryNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, something went wrong during registration. Please try again in a few minutes.
        /// </summary>
        public static string AccountRegisterationFailed {
            get {
                return ResourceManager.GetString("AccountRegisterationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Cart Field!.
        /// </summary>
        public static string AddCartItemError {
            get {
                return ResourceManager.GetString("AddCartItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Is Required.
        /// </summary>
        public static string AddressIsRequired {
            get {
                return ResourceManager.GetString("AddressIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Must Read And Accept Agreement to use our services..
        /// </summary>
        public static string AgreementRequired {
            get {
                return ResourceManager.GetString("AgreementRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Cant Be Deleted !.
        /// </summary>
        public static string AlbumCantDelete {
            get {
                return ResourceManager.GetString("AlbumCantDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Cant Be Updated!.
        /// </summary>
        public static string AlbumCantUpdate {
            get {
                return ResourceManager.GetString("AlbumCantUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating new album !.
        /// </summary>
        public static string AlbumCreationFailed {
            get {
                return ResourceManager.GetString("AlbumCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while removing album !.
        /// </summary>
        public static string AlbumDeleteFailed {
            get {
                return ResourceManager.GetString("AlbumDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album has been expired !.
        /// </summary>
        public static string AlbumExpired {
            get {
                return ResourceManager.GetString("AlbumExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Is Locked.
        /// </summary>
        public static string AlbumIsLocked {
            get {
                return ResourceManager.GetString("AlbumIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Item Can&apos;t Be Deleted !.
        /// </summary>
        public static string AlbumItemCantBeDeleted {
            get {
                return ResourceManager.GetString("AlbumItemCantBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Photo Found For This Album Item !.
        /// </summary>
        public static string AlbumItemNotFound {
            get {
                return ResourceManager.GetString("AlbumItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Not Found !.
        /// </summary>
        public static string AlbumNotFound {
            get {
                return ResourceManager.GetString("AlbumNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating album !.
        /// </summary>
        public static string AlbumUpdateFailed {
            get {
                return ResourceManager.GetString("AlbumUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount are NotValid.
        /// </summary>
        public static string AmountNotValid {
            get {
                return ResourceManager.GetString("AmountNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photographer Arrival Time Must Be Before Exit Time !.
        /// </summary>
        public static string AttendanceTimeFromIsGreaterThanTo {
            get {
                return ResourceManager.GetString("AttendanceTimeFromIsGreaterThanTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photographer Arrival Time Can&apos;t be from past ! start time must be greater than now and at least 1 Hour Later !.
        /// </summary>
        public static string AttendanceTimeFromIsOver {
            get {
                return ResourceManager.GetString("AttendanceTimeFromIsOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photographer Arrival Time Can&apos;t be same as Exit Time !.
        /// </summary>
        public static string AttendanceTimeNotEqual {
            get {
                return ResourceManager.GetString("AttendanceTimeNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photographer Exit Time Must Be Greater Than Arrival Time !.
        /// </summary>
        public static string AttendanceTimeToIsLessThanFrom {
            get {
                return ResourceManager.GetString("AttendanceTimeToIsLessThanFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photographer Exit Time Can&apos;t be from past ! End time must be at least 1 Hour greater, than start time..
        /// </summary>
        public static string AttendanceToIsOver {
            get {
                return ResourceManager.GetString("AttendanceToIsOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization server is not available !.
        /// </summary>
        public static string AuthorizationServerNotAvailable {
            get {
                return ResourceManager.GetString("AuthorizationServerNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability Check Has Been Failed !.
        /// </summary>
        public static string AvailabilityCheckFailed {
            get {
                return ResourceManager.GetString("AvailabilityCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image quality is very bad !.
        /// </summary>
        public static string BadImageQuality {
            get {
                return ResourceManager.GetString("BadImageQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Out Of Service.
        /// </summary>
        public static string BankOutOfService {
            get {
                return ResourceManager.GetString("BankOutOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaching System Error !.
        /// </summary>
        public static string CacheError {
            get {
                return ResourceManager.GetString("CacheError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t delete this project in this state !.
        /// </summary>
        public static string CantDeleteProjectInThisState {
            get {
                return ResourceManager.GetString("CantDeleteProjectInThisState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Roll Back Prepayment !.
        /// </summary>
        public static string CantRollbackPrepayment {
            get {
                return ResourceManager.GetString("CantRollbackPrepayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart Is Empty.
        /// </summary>
        public static string CartEmpty {
            get {
                return ResourceManager.GetString("CartEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Not Found.
        /// </summary>
        public static string CategoryNotFound {
            get {
                return ResourceManager.GetString("CategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This chat is not exit !.
        /// </summary>
        public static string ChatNotFound {
            get {
                return ResourceManager.GetString("ChatNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat is disabled.
        /// </summary>
        public static string ChatRoomDisabled {
            get {
                return ResourceManager.GetString("ChatRoomDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat removed or is not exist anymore !.
        /// </summary>
        public static string ChatRoomIsNotExist {
            get {
                return ResourceManager.GetString("ChatRoomIsNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently we  dont service on your city. Axeto wil be available in your city.
        /// </summary>
        public static string CityCurrentlyNotAvailable {
            get {
                return ResourceManager.GetString("CityCurrentlyNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Credentials Are Required !.
        /// </summary>
        public static string ClientCredentialsRequired {
            get {
                return ResourceManager.GetString("ClientCredentialsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Access Has Been Locked.
        /// </summary>
        public static string ClientLocked {
            get {
                return ResourceManager.GetString("ClientLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Code has expired !.
        /// </summary>
        public static string CodeExpired {
            get {
                return ResourceManager.GetString("CodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment Not Allowed at This Time.
        /// </summary>
        public static string CommentNotAllowedThisTime {
            get {
                return ResourceManager.GetString("CommentNotAllowedThisTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concurrency error occurred.
        /// </summary>
        public static string ConcurrencyError {
            get {
                return ResourceManager.GetString("ConcurrencyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Parent Condition with child as not allowed.
        /// </summary>
        public static string ConditionHaveChild {
            get {
                return ResourceManager.GetString("ConditionHaveChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Confirm password does not match !.
        /// </summary>
        public static string ConfirmPasswordNotMatch {
            get {
                return ResourceManager.GetString("ConfirmPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, We Couldn&apos;t Verify You&apos;r Identity !.
        /// </summary>
        public static string Coudn_tVerifyIdentity {
            get {
                return ResourceManager.GetString("Coudn\'tVerifyIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access with this acount to this application is denied.
        /// </summary>
        public static string CrossLoginDenied {
            get {
                return ResourceManager.GetString("CrossLoginDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerId are Invalid.
        /// </summary>
        public static string CustomerIdInvalid {
            get {
                return ResourceManager.GetString("CustomerIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Entered Value Is Not Valid !.
        /// </summary>
        public static string DataEntryError {
            get {
                return ResourceManager.GetString("DataEntryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای محاسبه اختلاف زمانی !.
        /// </summary>
        public static string DateTimeCalculationFailed {
            get {
                return ResourceManager.GetString("DateTimeCalculationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decryption operation failed !.
        /// </summary>
        public static string DecryptionFailed {
            get {
                return ResourceManager.GetString("DecryptionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay Report Submited.
        /// </summary>
        public static string DelayReportSubmited {
            get {
                return ResourceManager.GetString("DelayReportSubmited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, something went wrong during the deletion. Please try again in a few minutes.
        /// </summary>
        public static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Code Is Invalid.
        /// </summary>
        public static string DiscountCodeIsInvalid {
            get {
                return ResourceManager.GetString("DiscountCodeIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Time Expired.
        /// </summary>
        public static string DiscountExpired {
            get {
                return ResourceManager.GetString("DiscountExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Limitation Times Error.
        /// </summary>
        public static string DiscountLimitationTimes {
            get {
                return ResourceManager.GetString("DiscountLimitationTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error While Downloading !.
        /// </summary>
        public static string DownloadError {
            get {
                return ResourceManager.GetString("DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download operation has been failed !.
        /// </summary>
        public static string DownloadFailed {
            get {
                return ResourceManager.GetString("DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate !.
        /// </summary>
        public static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email was used by someone else. If this email belongs to you, try to recover your account by email..
        /// </summary>
        public static string EmailAlreadyUsed {
            get {
                return ResourceManager.GetString("EmailAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty !.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message can&apos;t be empty !.
        /// </summary>
        public static string EmptyMessage {
            get {
                return ResourceManager.GetString("EmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption process has been failed !.
        /// </summary>
        public static string EncryptionFailed {
            get {
                return ResourceManager.GetString("EncryptionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occured !.
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving.
        /// </summary>
        public static string ErrorSave {
            get {
                return ResourceManager.GetString("ErrorSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 days remain for Extend Storing Album for 1 day.
        /// </summary>
        public static string ExtendAlbumTime {
            get {
                return ResourceManager.GetString("ExtendAlbumTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was not successful.
        /// </summary>
        public static string FailedOperation {
            get {
                return ResourceManager.GetString("FailedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file type is not allowed to upload !.
        /// </summary>
        public static string FileFormatIsNowAllowed {
            get {
                return ResourceManager.GetString("FileFormatIsNowAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found !.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0] signature is not valid !.
        /// </summary>
        public static string FileSignatureNotValid {
            get {
                return ResourceManager.GetString("FileSignatureNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size is less than {0} mb !.
        /// </summary>
        public static string FileSizeIsLessThanMb {
            get {
                return ResourceManager.GetString("FileSizeIsLessThanMb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size is more than {0} mb !.
        /// </summary>
        public static string FileSizeIsMoreThanMb {
            get {
                return ResourceManager.GetString("FileSizeIsMoreThanMb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway server is not available !.
        /// </summary>
        public static string GatewayServerNotAvailable {
            get {
                return ResourceManager.GetString("GatewayServerNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Content Is Illegal !.
        /// </summary>
        public static string IllegalPhotoContent {
            get {
                return ResourceManager.GetString("IllegalPhotoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessing to this content is limited !.
        /// </summary>
        public static string ImageAccessIsPrivate {
            get {
                return ResourceManager.GetString("ImageAccessIsPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Already Exist.
        /// </summary>
        public static string ImageAlreadyExist {
            get {
                return ResourceManager.GetString("ImageAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image resolution is very low !.
        /// </summary>
        public static string ImageResolutionIsLow {
            get {
                return ResourceManager.GetString("ImageResolutionIsLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size is larger than {0} mb !.
        /// </summary>
        public static string ImageSizeIsLargerThanMb {
            get {
                return ResourceManager.GetString("ImageSizeIsLargerThanMb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size is less than {0} mb !.
        /// </summary>
        public static string ImageSizeIsLessThanMb {
            get {
                return ResourceManager.GetString("ImageSizeIsLessThanMb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is incorrect !.
        /// </summary>
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available at this time !.
        /// </summary>
        public static string InformationNotAvailable {
            get {
                return ResourceManager.GetString("InformationNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input blocked !.
        /// </summary>
        public static string InputBlocked {
            get {
                return ResourceManager.GetString("InputBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Integrity Failed.
        /// </summary>
        public static string IntegrityCheckFailed {
            get {
                return ResourceManager.GetString("IntegrityCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age is not valid !.
        /// </summary>
        public static string InvalidAge {
            get {
                return ResourceManager.GetString("InvalidAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Price Is Not Valid !.
        /// </summary>
        public static string InvalidAlbumPrice {
            get {
                return ResourceManager.GetString("InvalidAlbumPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان های شروع و پایان معتبر نمی باشند !.
        /// </summary>
        public static string InvalidAttendanceTime {
            get {
                return ResourceManager.GetString("InvalidAttendanceTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your credentials are invalid !.
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input data type is not valid !.
        /// </summary>
        public static string InvalidDataType {
            get {
                return ResourceManager.GetString("InvalidDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is not valid !.
        /// </summary>
        public static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time are not valid !.
        /// </summary>
        public static string InvalidDateTime {
            get {
                return ResourceManager.GetString("InvalidDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days are not valid !.
        /// </summary>
        public static string InvalidDays {
            get {
                return ResourceManager.GetString("InvalidDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Decryption Key !.
        /// </summary>
        public static string InvalidDecryptionKey {
            get {
                return ResourceManager.GetString("InvalidDecryptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is invalid !.
        /// </summary>
        public static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption key is not valid !.
        /// </summary>
        public static string InvalidEncryptionKey {
            get {
                return ResourceManager.GetString("InvalidEncryptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end time is not valid !.
        /// </summary>
        public static string InvalidEndTime {
            get {
                return ResourceManager.GetString("InvalidEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type is not valid !.
        /// </summary>
        public static string InvalidFileType {
            get {
                return ResourceManager.GetString("InvalidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filters are invalid !.
        /// </summary>
        public static string InvalidFilters {
            get {
                return ResourceManager.GetString("InvalidFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input format is not valid !.
        /// </summary>
        public static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image format is not valid !.
        /// </summary>
        public static string InvalidImageFormat {
            get {
                return ResourceManager.GetString("InvalidImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value length is not valid !.
        /// </summary>
        public static string InvalidInputLength {
            get {
                return ResourceManager.GetString("InvalidInputLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value is not valid !.
        /// </summary>
        public static string InvalidInputValue {
            get {
                return ResourceManager.GetString("InvalidInputValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplier Is Not Valid !.
        /// </summary>
        public static string InvalidMultiplier {
            get {
                return ResourceManager.GetString("InvalidMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The national code is not valid !.
        /// </summary>
        public static string InvalidNationalNumber {
            get {
                return ResourceManager.GetString("InvalidNationalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number is invalid !.
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Price Is Not Valid !.
        /// </summary>
        public static string InvalidPhotoPrice {
            get {
                return ResourceManager.GetString("InvalidPhotoPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepayment is not valid !.
        /// </summary>
        public static string InvalidPrepayment {
            get {
                return ResourceManager.GetString("InvalidPrepayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Code is not valid !.
        /// </summary>
        public static string InvalidQrCode {
            get {
                return ResourceManager.GetString("InvalidQrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start time is not valid !.
        /// </summary>
        public static string InvalidStartTime {
            get {
                return ResourceManager.GetString("InvalidStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Contains Invalid Characters !.
        /// </summary>
        public static string InvalidTextCharacters {
            get {
                return ResourceManager.GetString("InvalidTextCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time is not valid !.
        /// </summary>
        public static string InvalidTime {
            get {
                return ResourceManager.GetString("InvalidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Timezone Id !.
        /// </summary>
        public static string InvalidTimezone {
            get {
                return ResourceManager.GetString("InvalidTimezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Days Is Not Valid !.
        /// </summary>
        public static string InvalidTotalDays {
            get {
                return ResourceManager.GetString("InvalidTotalDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction is not valid !.
        /// </summary>
        public static string InvalidTransaction {
            get {
                return ResourceManager.GetString("InvalidTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Step Verification Code is not valid !.
        /// </summary>
        public static string InvalidTwoStepVerifyCode {
            get {
                return ResourceManager.GetString("InvalidTwoStepVerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User !.
        /// </summary>
        public static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is not valid !.
        /// </summary>
        public static string InvalidUsername {
            get {
                return ResourceManager.GetString("InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username Or Password.
        /// </summary>
        public static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judgement Request Cant Submited Because of buying Photo from album.
        /// </summary>
        public static string JudgementStopByePhoto {
            get {
                return ResourceManager.GetString("JudgementStopByePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service is limited to customers !.
        /// </summary>
        public static string LimitedToCustomers {
            get {
                return ResourceManager.GetString("LimitedToCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service is limited to editor providers !.
        /// </summary>
        public static string LimitedToEditorProviders {
            get {
                return ResourceManager.GetString("LimitedToEditorProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service is limited to photographer providers !.
        /// </summary>
        public static string LimitedToPhotographerProviders {
            get {
                return ResourceManager.GetString("LimitedToPhotographerProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service is limited to service providers !.
        /// </summary>
        public static string LimitedToServiceProviders {
            get {
                return ResourceManager.GetString("LimitedToServiceProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the maximum number of failed attempts !.
        /// </summary>
        public static string MaxAllowedTryReached {
            get {
                return ResourceManager.GetString("MaxAllowedTryReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum input characters is {0} !.
        /// </summary>
        public static string MaximumCharacters {
            get {
                return ResourceManager.GetString("MaximumCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Maximum Length is {0} !.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Maximum Length of {0} is 25 character !.
        /// </summary>
        public static string Maxlength25 {
            get {
                return ResourceManager.GetString("Maxlength25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project time can be up to {0} working hours !.
        /// </summary>
        public static string MaxProjectDurationIs {
            get {
                return ResourceManager.GetString("MaxProjectDurationIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project time can be up to 8 working hours !.
        /// </summary>
        public static string MaxProjectDurationIsEightHour {
            get {
                return ResourceManager.GetString("MaxProjectDurationIsEightHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This type of file is not allowed !.
        /// </summary>
        public static string MimeTypeNotAllowed {
            get {
                return ResourceManager.GetString("MimeTypeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum input characters is {0} !.
        /// </summary>
        public static string MinimumCharacters {
            get {
                return ResourceManager.GetString("MinimumCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Minimum Length is {0} !.
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Code Required.
        /// </summary>
        public static string NationalCodeRequired {
            get {
                return ResourceManager.GetString("NationalCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative numbers are not allowed !.
        /// </summary>
        public static string NegativeValueNotValid {
            get {
                return ResourceManager.GetString("NegativeValueNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Not Found Or Is Accepted Later.
        /// </summary>
        public static string NewOfferOperationField {
            get {
                return ResourceManager.GetString("NewOfferOperationField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Address Provided !.
        /// </summary>
        public static string NoAddressProvided {
            get {
                return ResourceManager.GetString("NoAddressProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Admin Are Available !.
        /// </summary>
        public static string NoAdminAvailable {
            get {
                return ResourceManager.GetString("NoAdminAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Blocked Money Yet.
        /// </summary>
        public static string NoBlockedMoney {
            get {
                return ResourceManager.GetString("NoBlockedMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Location Provided !.
        /// </summary>
        public static string NoLocationProvided {
            get {
                return ResourceManager.GetString("NoLocationProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Photo Provided !.
        /// </summary>
        public static string NoPhotoProvided {
            get {
                return ResourceManager.GetString("NoPhotoProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No service provider are available at this time !.
        /// </summary>
        public static string NoProviderAvailableAtThisTime {
            get {
                return ResourceManager.GetString("NoProviderAvailableAtThisTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No service provider found !.
        /// </summary>
        public static string NoProviderFound {
            get {
                return ResourceManager.GetString("NoProviderFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No service provider are free at this time !.
        /// </summary>
        public static string NoProviderFoundFreeTime {
            get {
                return ResourceManager.GetString("NoProviderFoundFreeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No service provider in this category are available at this time !.
        /// </summary>
        public static string NoProviderFoundInCategory {
            get {
                return ResourceManager.GetString("NoProviderFoundInCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No service provider in this city are available at this time !.
        /// </summary>
        public static string NoProviderFoundInCity {
            get {
                return ResourceManager.GetString("NoProviderFoundInCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Response Received !.
        /// </summary>
        public static string NoResponse {
            get {
                return ResourceManager.GetString("NoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Server Specifiedd !.
        /// </summary>
        public static string NoServerSpecified {
            get {
                return ResourceManager.GetString("NoServerSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Support Are Available !.
        /// </summary>
        public static string NoSupportAvailable {
            get {
                return ResourceManager.GetString("NoSupportAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Symbol character Allowed !.
        /// </summary>
        public static string NoSymbolAllowed {
            get {
                return ResourceManager.GetString("NoSymbolAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not album owner !.
        /// </summary>
        public static string NotAlbumOwner {
            get {
                return ResourceManager.GetString("NotAlbumOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Allowed !.
        /// </summary>
        public static string NotAllowed {
            get {
                return ResourceManager.GetString("NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input characters are not allowed !.
        /// </summary>
        public static string NotAllowedCharacters {
            get {
                return ResourceManager.GetString("NotAllowedCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Allowed For This Specialty.
        /// </summary>
        public static string NotAllowedForThisSpecialty {
            get {
                return ResourceManager.GetString("NotAllowedForThisSpecialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available !.
        /// </summary>
        public static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Confirmed Account.
        /// </summary>
        public static string NotConfirmedAccount {
            get {
                return ResourceManager.GetString("NotConfirmedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Enqueued !.
        /// </summary>
        public static string NotEnqueued {
            get {
                return ResourceManager.GetString("NotEnqueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Item Found !.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing Found !.
        /// </summary>
        public static string Nothing {
            get {
                return ResourceManager.GetString("Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Title Provided !.
        /// </summary>
        public static string NoTitleProvided {
            get {
                return ResourceManager.GetString("NoTitleProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Match !.
        /// </summary>
        public static string NotMatch {
            get {
                return ResourceManager.GetString("NotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not owner of this resource or have no permission to access !.
        /// </summary>
        public static string NotResourceOwner {
            get {
                return ResourceManager.GetString("NotResourceOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Yet Confirmed.
        /// </summary>
        public static string NotYetConfirmed {
            get {
                return ResourceManager.GetString("NotYetConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offensive Names Are Blocked !.
        /// </summary>
        public static string OffensiveNamesBlocked {
            get {
                return ResourceManager.GetString("OffensiveNamesBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offensive and Illegal Words Are Blocked !.
        /// </summary>
        public static string OffensiveWordsBlocked {
            get {
                return ResourceManager.GetString("OffensiveWordsBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Alpabetic characters are allowed.
        /// </summary>
        public static string OnlyAlpabet {
            get {
                return ResourceManager.GetString("OnlyAlpabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Numbers are allowed.
        /// </summary>
        public static string OnlyNumber {
            get {
                return ResourceManager.GetString("OnlyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order server is not available !.
        /// </summary>
        public static string OrderServerNotAvailable {
            get {
                return ResourceManager.GetString("OrderServerNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not match !.
        /// </summary>
        public static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Service Error.
        /// </summary>
        public static string PaymentServiceError {
            get {
                return ResourceManager.GetString("PaymentServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This phone number was used by someone else. If this number belongs to you, try to recover your account by phone number..
        /// </summary>
        public static string PhoneNumberAlreadyUsed {
            get {
                return ResourceManager.GetString("PhoneNumberAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Not Found ! may be removed or not exist..
        /// </summary>
        public static string PhotoNotFound {
            get {
                return ResourceManager.GetString("PhotoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepayment info is not available !.
        /// </summary>
        public static string PrepaymentNotAvailable {
            get {
                return ResourceManager.GetString("PrepaymentNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Project have an album already !.
        /// </summary>
        public static string ProjectAlbumAlreadyExist {
            get {
                return ResourceManager.GetString("ProjectAlbumAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Album found for this project !.
        /// </summary>
        public static string ProjectAlbumNotExist {
            get {
                return ResourceManager.GetString("ProjectAlbumNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Price Cant Assigned under prepayment.
        /// </summary>
        public static string ProjectALbumPriceValidationError {
            get {
                return ResourceManager.GetString("ProjectALbumPriceValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Alredy Done For Report.
        /// </summary>
        public static string ProjectAlredyDoneForReport {
            get {
                return ResourceManager.GetString("ProjectAlredyDoneForReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Has Been Cancelled !.
        /// </summary>
        public static string ProjectCancelled {
            get {
                return ResourceManager.GetString("ProjectCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project creation has been failed !.
        /// </summary>
        public static string ProjectCreationFailed {
            get {
                return ResourceManager.GetString("ProjectCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project time should be more than an hour !.
        /// </summary>
        public static string ProjectDurationIsZero {
            get {
                return ResourceManager.GetString("ProjectDurationIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Has Been Expired !.
        /// </summary>
        public static string ProjectExpired {
            get {
                return ResourceManager.GetString("ProjectExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Id Invalid.
        /// </summary>
        public static string ProjectIdInvalid {
            get {
                return ResourceManager.GetString("ProjectIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project offering is locked !.
        /// </summary>
        public static string ProjectOfferingLocked {
            get {
                return ResourceManager.GetString("ProjectOfferingLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project offering time has been ended !.
        /// </summary>
        public static string ProjectOfferingTimeExpired {
            get {
                return ResourceManager.GetString("ProjectOfferingTimeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Registeration Process Has Been Failed !.
        /// </summary>
        public static string ProjectProcessingFailed {
            get {
                return ResourceManager.GetString("ProjectProcessingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Uploading State will allowed you to create album.
        /// </summary>
        public static string ProjectStateIsNotUploading {
            get {
                return ResourceManager.GetString("ProjectStateIsNotUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project StateMust Done.
        /// </summary>
        public static string ProjectStateMustDone {
            get {
                return ResourceManager.GetString("ProjectStateMustDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Time Of project must greater than one hour.
        /// </summary>
        public static string ProjectUnderOneHour {
            get {
                return ResourceManager.GetString("ProjectUnderOneHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Failed !.
        /// </summary>
        public static string ReportFailed {
            get {
                return ResourceManager.GetString("ReportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required !.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset Failed !.
        /// </summary>
        public static string ResetPasswordFailed {
            get {
                return ResourceManager.GetString("ResetPasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the desired resource is restricted !.
        /// </summary>
        public static string ResourceAccessLimited {
            get {
                return ResourceManager.GetString("ResourceAccessLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Condition Error !.
        /// </summary>
        public static string SecurityConditionError {
            get {
                return ResourceManager.GetString("SecurityConditionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t Send Message at this time !.
        /// </summary>
        public static string SendMessageFail {
            get {
                return ResourceManager.GetString("SendMessageFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server or resouce is down !.
        /// </summary>
        public static string ServerOrResourceDown {
            get {
                return ResourceManager.GetString("ServerOrResourceDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Is Under High Load !.
        /// </summary>
        public static string ServiceLoadWarning {
            get {
                return ResourceManager.GetString("ServiceLoadWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheba Number Required.
        /// </summary>
        public static string ShebaNumberRequired {
            get {
                return ResourceManager.GetString("ShebaNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;r skill is not match !.
        /// </summary>
        public static string SkillNotMatch {
            get {
                return ResourceManager.GetString("SkillNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Pending.
        /// </summary>
        public static string SkillPending {
            get {
                return ResourceManager.GetString("SkillPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album can extend 0 days before Expiration.
        /// </summary>
        public static string SoonForExtendAlbum {
            get {
                return ResourceManager.GetString("SoonForExtendAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speciality Already Exist.
        /// </summary>
        public static string SpecialityAlreadyExist {
            get {
                return ResourceManager.GetString("SpecialityAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;r specialty not match !.
        /// </summary>
        public static string SpecialtyTypeNotMatch {
            get {
                return ResourceManager.GetString("SpecialtyTypeNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project 0 Rejected by selected Specialist .
        /// </summary>
        public static string SpRejectProject {
            get {
                return ResourceManager.GetString("SpRejectProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage server is not available !.
        /// </summary>
        public static string StorageServerNotAvailable {
            get {
                return ResourceManager.GetString("StorageServerNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only this formats are supported : {0}.
        /// </summary>
        public static string SupportedFileFormats {
            get {
                return ResourceManager.GetString("SupportedFileFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System is under upgrade. please wait a few minutes !.
        /// </summary>
        public static string SystemIsUnderUpgrade {
            get {
                return ResourceManager.GetString("SystemIsUnderUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System is not available at this time !.
        /// </summary>
        public static string SystemNotAvailable {
            get {
                return ResourceManager.GetString("SystemNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Number Required.
        /// </summary>
        public static string TelephoneNumberRequired {
            get {
                return ResourceManager.GetString("TelephoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Closed.
        /// </summary>
        public static string TicketClosed {
            get {
                return ResourceManager.GetString("TicketClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Token has expired !.
        /// </summary>
        public static string TokenExpired {
            get {
                return ResourceManager.GetString("TokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you have too many requests. Please try again after a while!.
        /// </summary>
        public static string ToManyRequest {
            get {
                return ResourceManager.GetString("ToManyRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is too long !.
        /// </summary>
        public static string TooLong {
            get {
                return ResourceManager.GetString("TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is too short !.
        /// </summary>
        public static string TooShort {
            get {
                return ResourceManager.GetString("TooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking Failed !.
        /// </summary>
        public static string TrackingFailed {
            get {
                return ResourceManager.GetString("TrackingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Step Verification Failed !.
        /// </summary>
        public static string TwoStepVerificationFailed {
            get {
                return ResourceManager.GetString("TwoStepVerificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Step Verification Required !.
        /// </summary>
        public static string TwoStepVerifyRequired {
            get {
                return ResourceManager.GetString("TwoStepVerifyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to authorize you&apos;r accessat this time. please try again or contact with support team..
        /// </summary>
        public static string UnableToAuthorization {
            get {
                return ResourceManager.GetString("UnableToAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your access is unauthorized !.
        /// </summary>
        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to access this resource !.
        /// </summary>
        public static string UnauthorizedResourceAccess {
            get {
                return ResourceManager.GetString("UnauthorizedResourceAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable !.
        /// </summary>
        public static string Unavailable {
            get {
                return ResourceManager.GetString("Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was unsuccessful !.
        /// </summary>
        public static string Unsuccessful {
            get {
                return ResourceManager.GetString("Unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, something went wrong while updating your profile! Please try again in a few minutes.
        /// </summary>
        public static string UnSuccessfullProfileUpdate {
            get {
                return ResourceManager.GetString("UnSuccessfullProfileUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, something went wrong during the update. Please try again in a few minutes.
        /// </summary>
        public static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload operation has been cancelled !.
        /// </summary>
        public static string UploadCancelled {
            get {
                return ResourceManager.GetString("UploadCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload operation has been failed !.
        /// </summary>
        public static string UploadFailed {
            get {
                return ResourceManager.GetString("UploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading time will not expired.
        /// </summary>
        public static string UploadingReportFaild {
            get {
                return ResourceManager.GetString("UploadingReportFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not in service providers group !.
        /// </summary>
        public static string UserIsNotProvider {
            get {
                return ResourceManager.GetString("UserIsNotProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username has already been chosen by someone else. Please select another username..
        /// </summary>
        public static string UsernameAlreadyUsed {
            get {
                return ResourceManager.GetString("UsernameAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username can&apos;t be phone number! please choose a good nickname as your identity..
        /// </summary>
        public static string UsernameCantBePhoneNo {
            get {
                return ResourceManager.GetString("UsernameCantBePhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name can&apos;t be same as your phone number! please choose you&apos;r name or nickname..
        /// </summary>
        public static string UserNameCantBeSameAsPhoneNo {
            get {
                return ResourceManager.GetString("UserNameCantBeSameAsPhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username has already been used by someone else !.
        /// </summary>
        public static string UsernameExist {
            get {
                return ResourceManager.GetString("UsernameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username is banned ! Please select a valid username..
        /// </summary>
        public static string UsernameIsBanned {
            get {
                return ResourceManager.GetString("UsernameIsBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username not found !.
        /// </summary>
        public static string UsernameNotFound {
            get {
                return ResourceManager.GetString("UsernameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found !.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Or More Validation Error Occurred !.
        /// </summary>
        public static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet balance is not enough.
        /// </summary>
        public static string Walletbalanceisnotenough {
            get {
                return ResourceManager.GetString("Walletbalanceisnotenough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can Send Only 1 Offer For This Project. you can remove and send a new one if you changed you&apos;r mind !.
        /// </summary>
        public static string YouAlreadyOfferedThisProject {
            get {
                return ResourceManager.GetString("YouAlreadyOfferedThisProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not owner of this resource !.
        /// </summary>
        public static string YouAreNotResourceOwner {
            get {
                return ResourceManager.GetString("YouAreNotResourceOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t cancel your offer at this state !.
        /// </summary>
        public static string YouCantCancelOfferAtThisState {
            get {
                return ResourceManager.GetString("YouCantCancelOfferAtThisState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t remove your offer at this state !.
        /// </summary>
        public static string YouCantDeleteOfferAtThisState {
            get {
                return ResourceManager.GetString("YouCantDeleteOfferAtThisState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t send offer for this type of project ! you may have no matched or confirmed skill..
        /// </summary>
        public static string YouCantOfferThisProjectType {
            get {
                return ResourceManager.GetString("YouCantOfferThisProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your access is blocked !.
        /// </summary>
        public static string YourAccessBlocked {
            get {
                return ResourceManager.GetString("YourAccessBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;r account is not active ! please first active your account !.
        /// </summary>
        public static string YourAccountIsDeActive {
            get {
                return ResourceManager.GetString("YourAccountIsDeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;r account is not confirmed yet ! please contact with support team or email support@axeto.net.
        /// </summary>
        public static string YourAccountIsNotConfirmed {
            get {
                return ResourceManager.GetString("YourAccountIsNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been temporarily locked due to repeated unsuccessful login attempts..
        /// </summary>
        public static string YourAccountLockedOut {
            get {
                return ResourceManager.GetString("YourAccountLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been temporarily locked due to repeated unsuccessful login attempts. please try again in {0} .
        /// </summary>
        public static string YourAccountLockedOutUntil {
            get {
                return ResourceManager.GetString("YourAccountLockedOutUntil", resourceCulture);
            }
        }
    }
}
