//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saeed.Utilities.LocalizedResource.InformationMessages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InformationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InformationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Saeed.Utilities.LocalizedResource.InformationMessages.InformationMessages", typeof(InformationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation Link Sent To Your Phone/Email.
        /// </summary>
        public static string ActivationLinkSent {
            get {
                return ResourceManager.GetString("ActivationLinkSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item was added successfully to cart.
        /// </summary>
        public static string AddCartSuccess {
            get {
                return ResourceManager.GetString("AddCartSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Ticket Success.
        /// </summary>
        public static string AddTicketSuccess {
            get {
                return ResourceManager.GetString("AddTicketSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum time required to reach the project site is 0 minutes. Please be careful with your schedule.
        /// </summary>
        public static string AffischTimeMessage {
            get {
                return ResourceManager.GetString("AffischTimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Created Successfully.
        /// </summary>
        public static string AlbumCreatedSuccessfully {
            get {
                return ResourceManager.GetString("AlbumCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album 0 Created Successfully.
        /// </summary>
        public static string AlbumCreatedSuccessfullySms {
            get {
                return ResourceManager.GetString("AlbumCreatedSuccessfullySms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Im Using Axeto.
        /// </summary>
        public static string BiographyEmpty {
            get {
                return ResourceManager.GetString("BiographyEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Full Album Complete.
        /// </summary>
        public static string BuyFullAlbumComplete {
            get {
                return ResourceManager.GetString("BuyFullAlbumComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Verify Cancellation.
        /// </summary>
        public static string CancellationVerify {
            get {
                return ResourceManager.GetString("CancellationVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to project State Changed to {0}.
        /// </summary>
        public static string ChangeProjectState {
            get {
                return ResourceManager.GetString("ChangeProjectState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading Standard Time Over. You Got Some Minus Points.
        /// </summary>
        public static string CheckUploadingTime {
            get {
                return ResourceManager.GetString("CheckUploadingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axeto Confirmation Link : {0}.
        /// </summary>
        public static string ConfirmLink {
            get {
                return ResourceManager.GetString("ConfirmLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If necessary, please contact support.
        /// </summary>
        public static string ContactSupportIfNeeded {
            get {
                return ResourceManager.GetString("ContactSupportIfNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A discount of {0}Tomans was applied.
        /// </summary>
        public static string DiscountAppliedSuccess {
            get {
                return ResourceManager.GetString("DiscountAppliedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributed Cache Is Not Available !.
        /// </summary>
        public static string DistributedCacheUnavailable {
            get {
                return ResourceManager.GetString("DistributedCacheUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End User Licence Agreement.
        /// </summary>
        public static string EULAPolicy {
            get {
                return ResourceManager.GetString("EULAPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend Album Successfully.
        /// </summary>
        public static string ExtendAlbumSuccessfully {
            get {
                return ResourceManager.GetString("ExtendAlbumSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client {0} Identity Has Been Rejected..
        /// </summary>
        public static string IdentityRejected {
            get {
                return ResourceManager.GetString("IdentityRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Providers Are Available !.
        /// </summary>
        public static string InquiryAvailable {
            get {
                return ResourceManager.GetString("InquiryAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Service Provider Are Available With This Conditions !.
        /// </summary>
        public static string InquiryNotAvailable {
            get {
                return ResourceManager.GetString("InquiryNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intrusion into the system was detected {0} !.
        /// </summary>
        public static string IntrusionDetected {
            get {
                return ResourceManager.GetString("IntrusionDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project 0 Judgement Result Goes to 1.
        /// </summary>
        public static string judgementStateChangeToFinal {
            get {
                return ResourceManager.GetString("judgementStateChangeToFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project 0 Judgement State Changed To 1.
        /// </summary>
        public static string JudgementStateToPend {
            get {
                return ResourceManager.GetString("JudgementStateToPend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to judgement Request Submited For Project 0.
        /// </summary>
        public static string JudgementSubmitedCu {
            get {
                return ResourceManager.GetString("JudgementSubmitedCu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an judgement request submited for project 0.
        /// </summary>
        public static string JudgementSubmitedSp {
            get {
                return ResourceManager.GetString("JudgementSubmitedSp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Login Attempt Detected {0} !.
        /// </summary>
        public static string MultipleLoginAttempt {
            get {
                return ResourceManager.GetString("MultipleLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Link Sent To Your Phone/Email.
        /// </summary>
        public static string PasswordLinkSent {
            get {
                return ResourceManager.GetString("PasswordLinkSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Request Pending.
        /// </summary>
        public static string PendingSkillMessage {
            get {
                return ResourceManager.GetString("PendingSkillMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your image was successfully uploaded. After confirmation, the photo will be placed in your profile.
        /// </summary>
        public static string PortfoSendSuccessfully {
            get {
                return ResourceManager.GetString("PortfoSendSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can buy 0 item from this album by prepayment .
        /// </summary>
        public static string PrePaymentRemainMessage {
            get {
                return ResourceManager.GetString("PrePaymentRemainMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepayments Done.
        /// </summary>
        public static string PrepaymentsDone {
            get {
                return ResourceManager.GetString("PrepaymentsDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;r request is under process.
        /// </summary>
        public static string Proccessing {
            get {
                return ResourceManager.GetString("Proccessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album expiration reminder for {0} project.
        /// </summary>
        public static string ProjectAlbumReminder {
            get {
                return ResourceManager.GetString("ProjectAlbumReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Not Found ForCity.
        /// </summary>
        public static string ProjectNotFoundForCity {
            get {
                return ResourceManager.GetString("ProjectNotFoundForCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Not Found For  your FreeTime.
        /// </summary>
        public static string ProjectNotFoundForFreeTime {
            get {
                return ResourceManager.GetString("ProjectNotFoundForFreeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Not Found For  your SKill.
        /// </summary>
        public static string ProjectNotFoundForSKill {
            get {
                return ResourceManager.GetString("ProjectNotFoundForSKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Not Found For your Speciality.
        /// </summary>
        public static string ProjectNotFoundForSpeciality {
            get {
                return ResourceManager.GetString("ProjectNotFoundForSpeciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Offer For {0} Project Is Accepted.
        /// </summary>
        public static string ProjectOfferAcceptedSpVersion {
            get {
                return ResourceManager.GetString("ProjectOfferAcceptedSpVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Project with your skills are available !.
        /// </summary>
        public static string ProjectOrdeAvailableEmailMessage {
            get {
                return ResourceManager.GetString("ProjectOrdeAvailableEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Order {0} Cancelled.
        /// </summary>
        public static string ProjectOrderCancelled {
            get {
                return ResourceManager.GetString("ProjectOrderCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Project Created Successfully, at {0}.
        /// </summary>
        public static string ProjectOrderCreatedEmailMessage {
            get {
                return ResourceManager.GetString("ProjectOrderCreatedEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Order {0} Expired.
        /// </summary>
        public static string ProjectOrderExpired {
            get {
                return ResourceManager.GetString("ProjectOrderExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Order {0} Is Pending.
        /// </summary>
        public static string ProjectOrderIsPending {
            get {
                return ResourceManager.GetString("ProjectOrderIsPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Offer Accepted.
        /// </summary>
        public static string ProjectOrderOfferAcceptedCuMessage {
            get {
                return ResourceManager.GetString("ProjectOrderOfferAcceptedCuMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Offer Accepted For {0} Project.
        /// </summary>
        public static string ProjectOrderOfferAcceptedSpMessage {
            get {
                return ResourceManager.GetString("ProjectOrderOfferAcceptedSpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Offer created for you&apos;r project order {0}.
        /// </summary>
        public static string ProjectOrderOfferCreatedEmailMessage {
            get {
                return ResourceManager.GetString("ProjectOrderOfferCreatedEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Order {0} Timing / Details Updated.
        /// </summary>
        public static string ProjectOrderTimingUpdated {
            get {
                return ResourceManager.GetString("ProjectOrderTimingUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Order {0} Updated.
        /// </summary>
        public static string ProjectOrderUpdated {
            get {
                return ResourceManager.GetString("ProjectOrderUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Project was deleted because of not  prepayment.
        /// </summary>
        public static string ProjectPrepaymentTimeOut {
            get {
                return ResourceManager.GetString("ProjectPrepaymentTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects Reminder.
        /// </summary>
        public static string ProjectsReminder {
            get {
                return ResourceManager.GetString("ProjectsReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Started.
        /// </summary>
        public static string ProjectStarted {
            get {
                return ResourceManager.GetString("ProjectStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project State Changed To Uploading.
        /// </summary>
        public static string ProjectStateUploading {
            get {
                return ResourceManager.GetString("ProjectStateUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Skill For Service Provider {1} Approved.
        /// </summary>
        public static string ProviderSkillApproved {
            get {
                return ResourceManager.GetString("ProviderSkillApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Skill For Service Provider {1} Rejected.
        /// </summary>
        public static string ProviderSkillRejected {
            get {
                return ResourceManager.GetString("ProviderSkillRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider {0} Specialty Changed.
        /// </summary>
        public static string ProviderSpecialtyChanged {
            get {
                return ResourceManager.GetString("ProviderSpecialtyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Rejected by Service Provider!.
        /// </summary>
        public static string RejectProjectSuccess {
            get {
                return ResourceManager.GetString("RejectProjectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are updating the server. Thank you for your patience..
        /// </summary>
        public static string ServerUnderUpdate {
            get {
                return ResourceManager.GetString("ServerUnderUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} is not reachable !.
        /// </summary>
        public static string ServiceIsNotReachable {
            get {
                return ResourceManager.GetString("ServiceIsNotReachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Provider Arrived?.
        /// </summary>
        public static string ServiceProviderArrived {
            get {
                return ResourceManager.GetString("ServiceProviderArrived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Offer is accepted.
        /// </summary>
        public static string SpAcceptOffer {
            get {
                return ResourceManager.GetString("SpAcceptOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account Confirmed Successfully.
        /// </summary>
        public static string spConfirmationSuccess {
            get {
                return ResourceManager.GetString("spConfirmationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to this Project denied beacuse of skill or speciality limit.
        /// </summary>
        public static string specialityAndSkillAccessDenied {
            get {
                return ResourceManager.GetString("specialityAndSkillAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speciality Submited Successfully, it will added after Accept by Admin.
        /// </summary>
        public static string SpecialitySubmitet {
            get {
                return ResourceManager.GetString("SpecialitySubmitet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been successfully verified.
        /// </summary>
        public static string SuccessfullAccountVerification {
            get {
                return ResourceManager.GetString("SuccessfullAccountVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploaded successfully.
        /// </summary>
        public static string SuccessfullFileUpload {
            get {
                return ResourceManager.GetString("SuccessfullFileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully logged in to your account.
        /// </summary>
        public static string SuccessfullLoggedIn {
            get {
                return ResourceManager.GetString("SuccessfullLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully logged out.
        /// </summary>
        public static string SuccessfullLoggedOut {
            get {
                return ResourceManager.GetString("SuccessfullLoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment was successful.
        /// </summary>
        public static string SuccessfullPayment {
            get {
                return ResourceManager.GetString("SuccessfullPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile has been updated successfully.
        /// </summary>
        public static string SuccessfullProfileUpdate {
            get {
                return ResourceManager.GetString("SuccessfullProfileUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet credit successfully charged.
        /// </summary>
        public static string SuccessfullWalletCharge {
            get {
                return ResourceManager.GetString("SuccessfullWalletCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done successfully.
        /// </summary>
        public static string Successfully {
            get {
                return ResourceManager.GetString("Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was successful.
        /// </summary>
        public static string SuccessfulOperation {
            get {
                return ResourceManager.GetString("SuccessfulOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0} ! We have noticed several unsuccessful attempts to sign in to your account at {1}. If you have forgotten your password, you can restore your account via the following address {2} . Otherwise ignore this message..
        /// </summary>
        public static string SuspiciousLoginAttemptsDetected {
            get {
                return ResourceManager.GetString("SuspiciousLoginAttemptsDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you !.
        /// </summary>
        public static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Reply Success.
        /// </summary>
        public static string TicketReplySuccess {
            get {
                return ResourceManager.GetString("TicketReplySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Authentication Flow Is Not Supported !.
        /// </summary>
        public static string UnsupportedProtocol {
            get {
                return ResourceManager.GetString("UnsupportedProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Success.
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uplade Delay Report Submited Successfully.
        /// </summary>
        public static string UploadReportToCustomer {
            get {
                return ResourceManager.GetString("UploadReportToCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You got Delay Report For Project.
        /// </summary>
        public static string UploadReportToServiceProvider {
            get {
                return ResourceManager.GetString("UploadReportToServiceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Agreement.
        /// </summary>
        public static string UserAgreement {
            get {
                return ResourceManager.GetString("UserAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Dear {0}.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YourAccountConfirmed.
        /// </summary>
        public static string YourAccountConfirmed {
            get {
                return ResourceManager.GetString("YourAccountConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YourAccountConfirmed. For activate your speciality check profile on this address https://serviceprovider.axeto.net and fill your profile..
        /// </summary>
        public static string YourAccountConfirmedPendOnProfile {
            get {
                return ResourceManager.GetString("YourAccountConfirmedPendOnProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account Not Verified !.
        /// </summary>
        public static string YourAccountNotVerified {
            get {
                return ResourceManager.GetString("YourAccountNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account Is Not Verified Yet !.
        /// </summary>
        public static string YourAccountNotVerifiedYet {
            get {
                return ResourceManager.GetString("YourAccountNotVerifiedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account Suspended !.
        /// </summary>
        public static string YourAccountSuspended {
            get {
                return ResourceManager.GetString("YourAccountSuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account Verified !.
        /// </summary>
        public static string YourAccountVerified {
            get {
                return ResourceManager.GetString("YourAccountVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your {0} album files will be deleted soon!.
        /// </summary>
        public static string YourAlbumFilesWillDeleteSoon {
            get {
                return ResourceManager.GetString("YourAlbumFilesWillDeleteSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your {0} album will expire in {1} !.
        /// </summary>
        public static string YourAlbumWillExpireIn {
            get {
                return ResourceManager.GetString("YourAlbumWillExpireIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your {0} skill is under review !.
        /// </summary>
        public static string YourSkillIsUnderReview {
            get {
                return ResourceManager.GetString("YourSkillIsUnderReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your {0} skill has been rejected!.
        /// </summary>
        public static string YourSkillRejected {
            get {
                return ResourceManager.GetString("YourSkillRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Skills Are Under Review.
        /// </summary>
        public static string YourSkillsAreUnderReview {
            get {
                return ResourceManager.GetString("YourSkillsAreUnderReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 Skills Cant added beacuse of not portfo added for them.
        /// </summary>
        public static string YourSkillsAreUnderReviewExept {
            get {
                return ResourceManager.GetString("YourSkillsAreUnderReviewExept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your {0} skill has been verified !.
        /// </summary>
        public static string YourSkillVerified {
            get {
                return ResourceManager.GetString("YourSkillVerified", resourceCulture);
            }
        }
    }
}
